### ISSUE TITLE
Wiki editieren

### ISSUE THREAD

**Issue by KoKoKotlin** [SebastianZug/CsharpCourse#15]
Man soll ja in das Wiki Beispiele von berühmten Softwarebugs einfügen. Ich konnte aber nicht herausfinden, wie man das Wiki editieren kann.

Auf der Hilfe-Seite von GitHub steht, dass man den Edit Button drücken muss, aber der ist scheinbar nur für den Owner des Repos sichtbar. Gibt es da eine andere Möglichkeit?

**Comment by SebastianZug** [comment]
Guten Morgen KoKoKotlin,
Danke für den Hinweis. Können Sie es bitte jetzt noch mal testen? 
Ich habe die Restriktiven Zugriffsrechte angepasst.
