### ISSUE TITLE
Partner für Teamarbeit

### ISSUE THREAD

**Issue by LinaTeumer** [SebastianZug/CsharpCourse#23]
Ein simples Problem: Die Anzahl an Freunden von mir die an diesem Kurs teilnimmt ist ungerade. 

Deshalb suche ich jetzt noch einen Parter für die Aufgaben die wir zu zweit lösen sollen 😄 
Wenn irgendwer auch noch niemand hat schreibt mir bitte eine Mail (ich hoffe man kann meine Mailadresse anschauen...).

**Comment by Speed-Rabbit14** [comment]
> Ein simples Problem: Die Anzahl an Freunden von mir die an diesem Kurs teilnimmt ist ungerade.
> Deshalb suche ich jetzt noch einen Parter für die Aufgaben die wir zu zweit lösen sollen 😄
> Wenn irgendwer auch noch niemand hat schreibt mir bitte eine Mail (ich hoffe man kann meine Mailadresse anschauen...).

Hi LinaTeumer,
bis jetzt habe ich das selbe Problem, doch zusammen können wir es lösen.
Deine E-Mail ist leider nicht sichtbar, du kannst mich aber gerne anschreiben.
MfG
Carl
