### ISSUE TITLE
Static Vars in C#

### ISSUE THREAD

**Issue by KoKoKotlin** [SebastianZug/CsharpCourse#39]
Wieso wird in diesem Beispiel die statische Variable Counter in einer extra Klasse angelegt, statt sie in der Programm Klasse anzulegen?

*Original:*
```cs
public static class Counter
  {
     public static int globalCounter = 0;
  }

  public class Program
  {
    static void IncrementsCounter(){
       Counter.globalCounter++;
    }
    public static void Main(string[] args){
      Console.WriteLine(Counter.globalCounter);
      IncrementsCounter();
      Console.WriteLine(Counter.globalCounter);
    }
  }
```

*Changed:*
```cs
  public class Program
  {
    private static int globalCounter = 0;
    
    static void IncrementsCounter(){
       globalCounter++;
    }
    public static void Main(string[] args){
      Console.WriteLine(globalCounter);
      IncrementsCounter();
      Console.WriteLine(globalCounter);
    }
  }
```

Im Grunde bietet die veränderte Variante genau die selbe Funktionalität, außer das die Counter Variable nicht in diesem zusätzlichen Namespace der Klasse ist. 
Ich finde immer, dass statische nicht konstante Felder einer Klasse `private` sein sollten, weil man das Programm sonst nur sehr schwer debuggen kann, weil auf die Variable von überall zugegriffen und geschrieben werden kann.

**Comment by SebastianZug** [comment]
Hallo @KoKoKotlin,

Sie haben natürlich recht mit allen Aussagen, die sie oben aufgeführt haben. Ich habe versucht mit dem Beispiel eine losgelöste globale Variable "nachzubilden", wie sie unter C++ realisierbar ist, Diese sollte außerhalb der spezifischen anderen Klasse (hier `Program`) liegt. Zugegebener Weise macht in der Struktur des Vorlesungbeispiel (lediglich eine referenzierende Klasse) nicht viel Sinn. Ich werde Ihr Beispiel ergänzen und die zugehörigen Erläuterungen einfügen.

Danke für den Hinweis!

Sebastian Zug
