### ISSUE TITLE
Ich habe Lust mit C# zu programmieren

### ISSUE THREAD

**Issue by SebastianZug** [SebastianZug/CsharpCourse#7]
# Warum?

Weil ...

**Comment by Nethiri** [comment]
Weil C# witzig ist :)

**Comment by SirNikOdTW** [comment]
Also, ich finde ja _Java_ schöner. _C#_ hat manche Konzepte in der Umsetzung, die viele anpreisen, mit denen ich nicht klar kommen. Dagegen finde ich die Konzepte in _Java_ manchmal besser. Aber das ist natürlich nur mein persönlicher Geschmack.

Aber in _C#_ finde ich es sehr cool, dass es **Operator-Überladungen** gibt. Durch die Operatorüberladung kann Code, z.B. bei der Vektorrechnung, sehr übersichtlich dargestellt werden und beinahe so, als würde man das auf Papier mathematisch aufschreiben. Alleine deshalb, hätte ich Lust ein kleines _C#_-Programm zu schreiben, um nur Operator.Überladung nutzen zu können und zu dürfen. Ansonsten hab ich mehr Lust auf _Java_

**Comment by Snikker123** [comment]
eigentlich habe **ich** _keine_ Lust, wenn ich ehrlich bin.... ;D

**Comment by KoKoKotlin** [comment]
Also meine persönliche Lieblingsprogrammiersprache ist tatsächlich Kotlin, weil diese viele Probleme, die es in Java gibt behebt und Objektorientierte Design noch um wichtige Funktionalitäten wie Operator Overloading erweitert und das Objektorientierte Paradigma mit dem Funktionalen gut verbindet.

Aber tatsächlich habe ich die Hoffnung, dass das bei C# auch der Fall sein wird, weil es noch eine eher neue Sprache ist und aus den Fehlern/Problemen der Vergangenheit (z.B. NullPointerException) lernen konnte.

**Comment by fjangfaragesh** [comment]
### Ich mag JavaScript (meistens)
Man kann mit JavaScript Probleme lösen:
```javascript
function problemLoesen(problem) {
   let loesung;
   do {
        console.log("Bin gleich fertig, dauert nicht mehr lange, muss nur noch kurz ...");
        loesung = neueLoesungSuchen(problem);
    } while (!problem.istLoesung(loesung))
    return loesung;
}

function neueLoesungSuchen(problem) {
    //um ehrlich zu sein, ich habe keine Ahnung, wie man das Problem löst...
    return Math.random();
}
```
_Klassen_ kann man auch benutzen, wenn man will

```javascript
class Problem {
    constructor(name,beschreibung) {
        this.name = name;
        this.beschreibung  = beschreibung;
    }
    istLoesung(x) {
        throw new Error("Problem.istLoesung is abstract");
    }
    toString() {
        return "Problem:" + this.name + " " + this.beschreibung;
    }
}
class GanzSchweresProblem extends Problem {
    constructor(name) {
        super(name,"Extrem schwer, ehrlich!");
    }
    istLoesung(x) {
         return Math.abs(0.7071067811865476-x) < 1e-15;
    }
}
```
Ich mag JavaScript, weil ...
- es eigentlich in in jedem Browser läuft
- Plattform unabhängig
- kleine Projekte schnell realisiert sind
- verknüpfung mit HTML erleichtert Grafische Benutzeroberfläche
- Texteditor und Browser ist zur Entwicklung ausreichend, man kann ohne irgendwas installieren zu müssen auf eigentlich jedem beliebigen Rechner entwickeln

Nachteile:

- fehlender Typenzwang und "just in time Compillierung" verursacht viele Fehler in Laufzeit
- nicht ganz so schnell, vorallem wenn man keine Ahnung Optimierung hat (so wie ich)
- kaum Daten Schreibrechte (kann man auch als Vorteil sehen, weil man nichts kaputt machen kann)
- einige spezielle Dinge sind Browserspezifisch

**Comment by LinaTeumer** [comment]
...ich keine Ahnung davon habe und deshalb auch nicht wie die meisten anderen hier irgendeine **tollere** _Variante_ kenne :)

**Comment by SebastianZug** [comment]
Danke für die aufschlussreichen Beiträge! @Snikker123  ... wir bemühen uns das zu ändern :-)
